### ISSUE TITLE
Sintaxe array depreciada no PHP 7.4

### ISSUE THREAD

**Issue by larsurilch** [eltoninacio/cpfcnpj-laravel#4]
Olá Elton,
Na versão PHP 7.4 a forma de escrever array com chaves está depreciada. Estou recebendo a seguinte mensagem de erro: **Array and string offset access syntax with curly braces is deprecated**.
No arquivo **eltoninacio/cpfcnpj-laravel/src/Validation/Cnpj.php** na **linha 34**. Acredito que no arquivo **eltoninacio/cpfcnpj-laravel/src/Validation/Cpf.php** aconteça o mesmo problema.
Olhando aqui no código tem algo como **$sum += $this->cnpj{$i} * $j;** enquanto a forma com a correção seria **$sum += $this->cnpj[$i] * $j;**
Abraço

**Comment by eltoninacio** [comment]
@larsurilch conforme sua observação fiz a corração do pacote subindo uma versão 2.0.1.
Obrigado pelo feedback.
Abraço

**Comment by larsurilch** [comment]
@eltoninacio obrigado pela correção. Acredito vc ter esquecido de atualizar o JSON. Fiz um um composer update e não fez nenhuma atualização.
